vertexColor:
  r: 100
  g: 100
  b: 100

vertexRadius: 10.0

showEdges: true

layoutConstants:
  scaling: 10.0
  gravity: 1.0
  jitterTolerance: 0.1
  isBarnesHutActive: false

communityDetectionConstants:
  resolution: 1.0
